In [2]:
import pandas as pd
data={
    "Name":["Amit" ,"Riya","Rahul","Priya","Karan"],
    "Age" :[20,21,20,22,21],
    "Department":["CSE","IT",'CSE',"ECE","IT"],
    "Marks" :[85,90,78,88,76]
}
df=pd.DataFrame(data)
df

    Name  Age Department  Marks
0   Amit   20        CSE     85
1   Riya   21         IT     90
2  Rahul   20        CSE     78
3  Priya   22        ECE     88
4  Karan   21         IT     76

# include 5 more rows in the dataframe
convert the different files format and
compare the file size

In [23]:

import pandas as pd
import os

# Create DataFrame
data = {
    "Name": ["Amit", "Riya", "Rahul", "Priya", "Karan"],
    "Age": [20, 21, 20, 22, 21],
    "Department": ["CSE", "IT", "CSE", "ECE", "IT"],
    "Marks": [85, 90, 78, 88, 76]
}

df = pd.DataFrame(data)

# Include 5 more rows in the DataFrame
new_data = {
    "Name": ["Neha", "Arjun", "Sneha", "Rohit", "Ananya"],
    "Age": [20, 22, 21, 20, 23],
    "Department": ["ECE", "CSE", "IT", "CSE", "ECE"],
    "Marks": [92, 81, 87, 79, 95]
}

df_new = pd.DataFrame(new_data)
df = pd.concat([df, df_new], ignore_index=True)

# Inspect the DataFrame
print("Shape:\n", df.shape)
print("Head with 3 rows:\n", df.head(3))
print("Tail of 2 rows:\n", df.tail(2))
print("Index:\n", df.index)
print("Columns:\n", df.columns.tolist())
print("Values:\n", df.values)
print("Data types:\n", df.dtypes)
print("Statistics:\n", df.describe())
print("Information:")
df.info()

# Convert into different file formats
df.to_csv("students.csv", index=False)
df.to_excel("students.xlsx", index=False)
df.to_json("students.json", orient="records", indent=4)
df.to_parquet("students.parquet", index=False)

# Compare file sizes
files = ["students.csv", "students.xlsx", "students.json", "students.parquet"]

print("\nFile Size Comparison:")
for file in files:
    size = os.path.getsize(file)
    print(file, ":", size, "bytes")

Shape:
 (10, 4)
Head with 3 rows:
     Name  Age Department  Marks
0   Amit   20        CSE     85
1   Riya   21         IT     90
2  Rahul   20        CSE     78
Tail of 2 rows:
      Name  Age Department  Marks
8   Rohit   20        CSE     79
9  Ananya   23        ECE     95
Index:
 RangeIndex(start=0, stop=10, step=1)
Columns:
 ['Name', 'Age', 'Department', 'Marks']
Values:
 [['Amit' 20 'CSE' 85]
 ['Riya' 21 'IT' 90]
 ['Rahul' 20 'CSE' 78]
 ['Priya' 22 'ECE' 88]
 ['Karan' 21 'IT' 76]
 ['Neha' 20 'ECE' 92]
 ['Arjun' 22 'CSE' 81]
 ['Sneha' 21 'IT' 87]
 ['Rohit' 20 'CSE' 79]
 ['Ananya' 23 'ECE' 95]]
Data types:
 Name          object
Age            int64
Department    object
Marks          int64
dtype: object
Statistics:
              Age      Marks
count  10.000000  10.000000
mean   21.000000  85.100000
std     1.054093   6.402257
min    20.000000  76.000000
25%    20.000000  79.500000
50%    21.000000  86.000000
75%    21.750000  89.500000
max    23.000000  95.000000
Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        10 non-null     object
 1   Age         10 non-null     int64
 2   Department  10 non-null     object
 3   Marks       10 non-null     int64
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes

File Size Comparison:
students.csv : 181 bytes
students.xlsx : 5214 bytes
students.json : 1017 bytes
students.parquet : 2891 bytes

In [7]:
#Inspect the DataFrame
print("Shape:\n",df.shape)
print("head with 3 rows:\n",df.head(3))
print("tail of 2 rows:\n",df.tail(2))
print("Index:\n",df.index)
print("Columns:\n",df.columns.tolist)
print("Values:\n",df.values)
print("Data types:\n",df.dtypes)
print("Statistics:\n",df.describe)
print("Information:\n",df.info())

Shape:
 (5, 4)
head with 3 rows:
     Name  Age Department  Marks
0   Amit   20        CSE     85
1   Riya   21         IT     90
2  Rahul   20        CSE     78
tail of 2 rows:
     Name  Age Department  Marks
3  Priya   22        ECE     88
4  Karan   21         IT     76
Index:
 RangeIndex(start=0, stop=5, step=1)
Columns:
 <bound method IndexOpsMixin.tolist of Index(['Name', 'Age', 'Department', 'Marks'], dtype='object')>
Values:
 [['Amit' 20 'CSE' 85]
 ['Riya' 21 'IT' 90]
 ['Rahul' 20 'CSE' 78]
 ['Priya' 22 'ECE' 88]
 ['Karan' 21 'IT' 76]]
Data types:
 Name          object
Age            int64
Department    object
Marks          int64
dtype: object
Statistics:
 <bound method NDFrame.describe of     Name  Age Department  Marks
0   Amit   20        CSE     85
1   Riya   21         IT     90
2  Rahul   20        CSE     78
3  Priya   22        ECE     88
4  Karan   21         IT     76>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Age         5 non-null      int64
 2   Department  5 non-null      object
 3   Marks       5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes
Information:
 None

In [9]:
iris=pd.read_csv("/content/Iris.csv")
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [12]:
print(iris.shape)
print(iris.columns)
print(iris.dtypes)

(150, 6)
Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')
Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

#File Formats
1. csv
2. excel
3. json
4. parquet

In [15]:
#load the dataset in the file format
iris.to_csv("iris_csvoutput.csv",index=False)
#Read the saved dataset
iris_csv=pd.read_csv("/content/iris_csvoutput.csv")
print(iris_csv.head)

<bound method NDFrame.head of       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns]>

In [16]:
iris.to_excel("iris_exceloutput.xlsx",index=False)
#load
iris_excel=pd.read_excel("/content/iris_exceloutput.xlsx")
print(iris_excel.tail(10))

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
140  141            6.7           3.1            5.6           2.4
141  142            6.9           3.1            5.1           2.3
142  143            5.8           2.7            5.1           1.9
143  144            6.8           3.2            5.9           2.3
144  145            6.7           3.3            5.7           2.5
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
140  Iris-virginica
141  Iris-virginica
142  Iris-virginica
143  Iris-virginica
144  Iris-virginica
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

In [17]:
# Json file format
iris.to_json("iris_jsonoutput.json",orient="records",index=4)
#load
iris_json=pd.read_json("/content/iris_jsonoutput.json",orient="records")
print(iris_json.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [18]:
#file format parquet
iris.to_parquet("iris_parquetoutput.parquet",index=False)
# read
iris_parquet=pd.read_parquet("/content/iris_parquetoutput.parquet")
print(iris_parquet.head(3))

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa

In [20]:
#Compare the size of the file format
import os
files=[
    "iris_csvoutput.csv",
    "iris_exceloutput.xlsx",
    "iris_jsonoutput.json",
    "iris_parquetoutput.parquet"
]
for file in files:
  size=os.path.getsize(file)
  print(f"{file}:{size} bytes")

iris_csvoutput.csv:5107 bytes
iris_exceloutput.xlsx:9208 bytes
iris_jsonoutput.json:17193 bytes
iris_parquetoutput.parquet:5932 bytes

In [21]:
# load the selscted columns
iris_small=pd.read_csv("/content/Iris.csv",usecols=["Id","SepalLengthCm","Species"])
print(iris_small.head(3))

   Id  SepalLengthCm      Species
0   1            5.1  Iris-setosa
1   2            4.9  Iris-setosa
2   3            4.7  Iris-setosa

In [22]:
#filter the data
result=iris[iris["SepalLengthCm"]>6]
result.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
50,51,7.0,3.2,4.7,1.4,Iris-versicolor
51,52,6.4,3.2,4.5,1.5,Iris-versicolor
52,53,6.9,3.1,4.9,1.5,Iris-versicolor
54,55,6.5,2.8,4.6,1.5,Iris-versicolor
56,57,6.3,3.3,4.7,1.6,Iris-versicolor